# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

FROM --platform=$BUILDPLATFORM docker.io/rust:1.98.0@sha256:620dbcd124499c59e2406d3741574b5c5838cf9eb9656f0c3a03948f79b02959 AS dataflow-build

WORKDIR /build/rust/dataflow
ARG BUILDPLATFORM
ARG TARGETPLATFORM
ARG FEATURES=kafka-receiver,kafka-exporter
ARG RUSTFLAGS="-C target-cpu=native"
ENV FEATURES=${FEATURES}
ENV RUSTFLAGS=${RUSTFLAGS}

RUN apt-get update && apt-get install -y clang libclang-dev protobuf-compiler

COPY --from=otel-arrow /proto/opentelemetry/proto /build/proto/opentelemetry/proto
COPY --from=otel-arrow /proto/opentelemetry-proto /build/proto/opentelemetry-proto
COPY --from=otel-arrow /rust/experimental /build/rust/experimental
COPY --from=otel-arrow /THIRD_PARTY_NOTICES.txt /build/THIRD_PARTY_NOTICES.txt
COPY . /build/rust/dataflow/.

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/build/rust/dataflow/target \
    sed -i 's/\r$//' cross-arch-build.sh && ./cross-arch-build.sh

FROM gcr.io/distroless/cc-debian13:nonroot@sha256:d97bc0a941b8d4be647dc0ee75b264ddbb772f1ac5ba690a4309c00723b23775
WORKDIR /home/nonroot
COPY --from=dataflow-build --chown=nonroot:nonroot /build/rust/dataflow/df_engine .
USER nonroot
ENTRYPOINT ["/home/nonroot/df_engine"]
